### ISSUE TITLE
How can I handle retry strategies using ReactiveCrudRepository?

### ISSUE THREAD

**Issue by albertbalada** [pioardi/Spring-Reactive#1]
What's the best way to define cassandra retry strategies using ReactiveCrudRepository

**Comment by pioardi** [comment]
Hi Albert , please see this commit https://github.com/pioardi/Spring-Reactive/commit/973451587af9830b1f1da472bb187057edd4a1fa . 
In particular files HotelController.java and application.properties changes .

For more info on spring boot properties on cassandra https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html . 

In this commit there is a reference for default retry strategy and case by case strategy ) , the same for consistency level .

**Comment by pioardi** [comment]
Another important ref   https://github.com/spring-projects/spring-data-examples/tree/master/cassandra/reactive    😃
