### ISSUE TITLE
How can I replace the opensource cassandra driver with the datastax one?

### ISSUE THREAD

**Issue by albertbalada** [pioardi/Spring-Reactive#2]
By default the Crud repository uses the community driver, how can we use the datastax one instead?

**Comment by pioardi** [comment]
Hi Albert ,
this commit https://github.com/pioardi/Spring-Reactive/commit/24d6864b11ed0bb334c7190f12369d6b5a698127 ( pom.xml file) should address your request .

Resources : 
https://github.com/tolbertam/spring-data-dse-driver-example .

Let me know if i can close this issue or if you need other infos .
